### ISSUE TITLE
Why is prototype folder zipped?

### ISSUE THREAD

**Issue by andybak** [Donut-Studios/Unity3D-Open-Source-AI-and-Procedural-Generation#1]
Rather negates the usefulness of using a VCS - with very few advantages that I can think of.

**Comment by micmelesse** [comment]
The archive is just a compiled demo of the code. It is there for convenience.

**Comment by andybak** [comment]
The readme is confusing then. It says:

> The Prototype archive contains a buildable Unity project folder

Note "Buildable" not "Built"... 

If the zip contains sources then it shouldn't really be zipped. If it actually contains compiled code then it might be worth rewording the readme.

(I'd check which it is myself but I'm not near a real PC)

**Comment by ragymorkos** [comment]
Hi Andy, thanks for your interest in our repo! You are actually right in that it doesn't make sense to have an archive in Github. We had to organise it this way because that's how our initial target audience wanted it to look like. I just pushed the changes and reworded the readme so it is in a folder now.

P.S: Last time I checked Unity did some major changes to their software and the Prototype folder didn't compile successfully. It should be just a simple change in their API that is causing this so this is where you will find the src folder to be helpful since it's the pure code or source data we wrote/produced without any compilation files. But anyways, I guess this is where having a folder for the compiled files would be helpful since we can just update whatever is causing the issue (once we figure it out).

I'm going to close this issue now but feel free to open a new one should anything else pop up!
